[project]
name = "llms-scalable-deliberation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.100.2",
    "pandas>=2.3.2",
]
