{
    "token": 'fx7-u1OlgKTV8-AlzPXDakxogdwdTfuNnPhgqHbCdZVD6sa6bkw8UkJVu-zi28Y8y3Q2vPiGYCyRX3jwJ06--Xna6pOuryNN937u2K_osLh1QN6qfwLTroQ4',
    "study_id": '68cc5f908546dbd818268144',
    "max_concurrent_sessions": 100,
    "workload_checker_period": 60
}