{
    "token": '5Emsl5cC_oSB0letz2LUJ7hncq5YefgQ1Y8EeQ8WR6onTKXHjXxK1ojld8tW8GXbzy67HL-0Zr2boTT_MdayfZLeXQ794I99wsBlEgsPfQmGtOy55sGk0B9z',
    "study_id": '68b9197d9b31d549f9ca7f4c',
    "max_concurrent_sessions": 30,
    "workload_checker_period": 60
}