{
    "token": 'fx7-u1OlgKTV8-AlzPXDakxogdwdTfuNnPhgqHbCdZVD6sa6bkw8UkJVu-zi28Y8y3Q2vPiGYCyRX3jwJ06--Xna6pOuryNN937u2K_osLh1QN6qfwLTroQ4',
    "study_id": '68ca220cc05a131c58d36395',
    "max_concurrent_sessions": 100,
    "workload_checker_period": 60
}